name: Docker CI
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Connect to Tailscale
              uses: tailscale/github-action@v1
              with:
                  authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
            - name: Build and deploy on server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd /home/bps-ubuntu/MyBPHS
                      git pull
                      npm install
                      npm run build
                      pm2 restart mybphs
